---
#
## 1vs1 v1.0.1 configuration file
#

# Kits are randomly selected
kits:
  diamond:
    helmet: [310, 0, 1] # [id, damage, count]
    chestplate: [311, 0, 1]
    leggings: [312, 0, 1]
    boots: [313, 0, 1]
    0: [267, 0, 1] # 1. inventory slot
    1: [322, 0, 5] # 2. inventory slot
    8: [364, 0, 16] # 9. inventory slot
  #steve: [] # add more kits like 'steve' kit here without any items

# Set false to disable hunger in game
hunger: true
...